-- MySQL Script generated by MySQL Workbench
-- Tue Mar 31 16:04:00 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema kovid
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kovid
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kovid` DEFAULT CHARACTER SET utf8 ;
USE `kovid` ;

-- -----------------------------------------------------
-- Table `kovid`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kovid`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kovid`.`Report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kovid`.`Report` (
  `Report_Id` INT NOT NULL AUTO_INCREMENT,
  `Report_ShortName` VARCHAR(45) NOT NULL,
  `Report_Name` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`Report_Id`),
  UNIQUE INDEX `Report_Id_UNIQUE` (`Report_Id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kovid`.`ReportSched`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kovid`.`ReportSched` (
  `Sched_Id` INT NOT NULL,
  `Schedule` VARCHAR(45) NOT NULL,
  `Report_Id` INT NOT NULL,
  PRIMARY KEY (`Sched_Id`, `Report_Id`),
  UNIQUE INDEX `Sched_Id_UNIQUE` (`Sched_Id` ASC),
  INDEX `fk_ReportSched_Report_idx` (`Report_Id` ASC),
  CONSTRAINT `fk_ReportSched_Report`
    FOREIGN KEY (`Report_Id`)
    REFERENCES `kovid`.`Report` (`Report_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kovid`.`ReportArguments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kovid`.`ReportArguments` (
  `Argument_Id` INT NOT NULL,
  `Argument_Key` VARCHAR(45) NOT NULL,
  `Report_Id` INT NOT NULL,
  `Argument_Value` VARCHAR(45) NOT NULL,
  `Argument_Type` VARCHAR(1) NOT NULL,
  `ReportArgumentscol` VARCHAR(45) NULL,
  PRIMARY KEY (`Argument_Id`, `Report_Id`),
  UNIQUE INDEX `Argument_Id_UNIQUE` (`Argument_Id` ASC),
  INDEX `fk_ReportArguments_Report1_idx` (`Report_Id` ASC),
  CONSTRAINT `fk_ReportArguments_Report1`
    FOREIGN KEY (`Report_Id`)
    REFERENCES `kovid`.`Report` (`Report_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kovid`.`ReportDestination`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kovid`.`ReportDestination` (
  `Dest_Mail` VARCHAR(250) NULL,
  `Report_Id` INT NOT NULL,
  `Dest_Id` INT NOT NULL,
  `Active` VARCHAR(1) NOT NULL DEFAULT 'N',
  `Dest_Type` VARCHAR(1) NOT NULL,
  `Dest_Object` VARCHAR(50) NULL,
  `Dest_Subject` VARCHAR(1000) NULL,
  INDEX `fk_ReportDestination_Report1_idx` (`Report_Id` ASC),
  PRIMARY KEY (`Report_Id`, `Dest_Id`),
  CONSTRAINT `fk_ReportDestination_Report1`
    FOREIGN KEY (`Report_Id`)
    REFERENCES `kovid`.`Report` (`Report_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kovid`.`Dest_Specs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kovid`.`Dest_Specs` (
  `Dest_Host` VARCHAR(250) NULL,
  `Dest_Path` VARCHAR(250) NULL,
  `Destination_Report_Id` INT NOT NULL,
  `Destination_Dest_Id` INT NOT NULL,
  INDEX `fk_Dest_ReportDestination1_idx` (`Destination_Report_Id` ASC, `Destination_Dest_Id` ASC),
  CONSTRAINT `fk_Dest_ReportDestination1`
    FOREIGN KEY (`Destination_Report_Id` , `Destination_Dest_Id`)
    REFERENCES `kovid`.`ReportDestination` (`Report_Id` , `Dest_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kovid`.`report_Execution`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kovid`.`report_Execution` (
  `Exec_Id` INT NOT NULL,
  `Start_Date` DATETIME NOT NULL,
  `End_Date` DATETIME NULL,
  `Status` VARCHAR(2) NULL,
  `Report_Id` INT NOT NULL,
  `Path` VARCHAR(250) NULL,
  PRIMARY KEY (`Exec_Id`, `Report_Id`),
  INDEX `fk_report_Execution_Report1_idx` (`Report_Id` ASC),
  CONSTRAINT `fk_report_Execution_Report1`
    FOREIGN KEY (`Report_Id`)
    REFERENCES `kovid`.`Report` (`Report_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
