-- MySQL Script generated by MySQL Workbench
-- Mon Mar 30 12:01:28 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

/* SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0; */
/* SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0; */
/* SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES'; */

-- -----------------------------------------------------
-- Schema kovid
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kovid
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS kovid DEFAULT CHARACTER SET utf8 ;
USE kovid ;

-- -----------------------------------------------------
-- Table `kovid`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS kovid.table1 (
)
;


-- -----------------------------------------------------
-- Table `kovid`.`Report`
-- -----------------------------------------------------
CREATE SEQUENCE kovid.Report_seq;

CREATE TABLE IF NOT EXISTS kovid.Report (
  Report_Id INT NOT NULL DEFAULT NEXTVAL ('kovid.Report_seq'),
  Report_ShortName VARCHAR(45) NOT NULL,
  Report_Name VARCHAR(250) NULL,
  PRIMARY KEY (Report_Id),
  CONSTRAINT Report_Id_UNIQUE UNIQUE  (Report_Id ASC))
;


-- -----------------------------------------------------
-- Table `kovid`.`ReportSched`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS kovid.ReportSched (
  Sched_Id INT NOT NULL,
  Schedule VARCHAR(45) NULL,
  Report_Id INT NOT NULL,
  PRIMARY KEY (Sched_Id, Report_Id),
  CONSTRAINT Sched_Id_UNIQUE UNIQUE  (Sched_Id ASC)
 ,
  CONSTRAINT fk_ReportSched_Report
    FOREIGN KEY (Report_Id)
    REFERENCES kovid.Report (Report_Id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;

CREATE INDEX fk_ReportSched_Report_idx ON kovid.ReportSched (Report_Id ASC);


-- -----------------------------------------------------
-- Table `kovid`.`ReportArguments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS kovid.ReportArguments (
  Argument_Id INT NOT NULL,
  Argument_Key VARCHAR(45) NOT NULL,
  Report_Id INT NOT NULL,
  Argument_Value VARCHAR(45) NOT NULL,
  PRIMARY KEY (Argument_Id, Report_Id),
  CONSTRAINT Argument_Id_UNIQUE UNIQUE  (Argument_Id ASC)
 ,
  CONSTRAINT fk_ReportArguments_Report1
    FOREIGN KEY (Report_Id)
    REFERENCES kovid.Report (Report_Id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;

CREATE INDEX fk_ReportArguments_Report1_idx ON kovid.ReportArguments (Report_Id ASC);


-- -----------------------------------------------------
-- Table `kovid`.`ReportDestination`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS kovid.ReportDestination (
  Destination VARCHAR(250) NOT NULL,
  Report_Id INT NOT NULL
 ,
  PRIMARY KEY (Report_Id),
  CONSTRAINT fk_ReportDestination_Report1
    FOREIGN KEY (Report_Id)
    REFERENCES kovid.Report (Report_Id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;

CREATE INDEX fk_ReportDestination_Report1_idx ON kovid.ReportDestination (Report_Id ASC);


/* SET SQL_MODE=@OLD_SQL_MODE; */
/* SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS; */
/* SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS; */
