name: CI Build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
      
      - name: Build the docker-compose stack
        working-directory: ./KoRe
        run: docker-compose -f docker-compose.yml up -d
        
      - name: Check running containers
        run: docker ps -a
        
      - name: Check logs
        run: docker-compose logs front
